import Menu from './menu.svg'
import Facebook from './facebook.svg'
import Tiktok from './tiktok.svg'
import Instagram from './instagram.svg'
import Youtube from './youtube.svg'
import Twitter from './twitter.svg'
import Screen from './screen.svg'
import Message from './message.svg'
import Paper from './paper.svg'
import MessageCircle from './message-circle.svg'
import Cart from './cart.svg'
import MenuMobile from './menu-mob.svg'
import Sv1 from './s1.svg'
import Sv2 from './s2.svg'
import Sv3 from './s3.svg'
import Sv4 from './s4.svg'
import Vec2 from './vec2.svg'
import Play from './play.svg'
import User from './user.svg'
import Comment from './comment.svg'

export {Menu, Facebook, Instagram, Tiktok, Youtube, Twitter, Screen, Message, Paper, MessageCircle, Cart, MenuMobile, Sv1, Sv2, Sv3, Sv4, Vec2, Play, User, Comment}