import bgHeader from './header4.jpg'
import Logo from './logo.svg'
import BgShap from './about_shaps.png'
import Ab1 from './ab1.jpg'
import Ab2 from './ab2.jpg'
import SerBg1 from './ser_bg1.jpg'
import SerBg2 from './ser_bg2.jpg'
import SerBg3 from './ser_bg3.jpg'
import SerBg4 from './ser_bg4.jpg'
import MenuItem1 from './1.jpg'
import MenuItem2 from './2.jpg'
import MenuItem3 from './3.jpg'
import MenuItem4 from './4.jpg'
import MenuItem5 from './5.jpg'
import MenuItem6 from './6.jpg'
import MenuItem7 from './7.jpg'
import MenuItem8 from './8.jpg'
import MenuItem9 from './9.jpg'
import MenuItem10 from './10.jpg'
import Member1 from './member-1.jpg'
import Member2 from './member-2.jpg'
import Member3 from './member-3.jpg'
import Member4 from './member-4.jpg'
import VideoImg from './vid_bg.jpg'
import Blog1 from './blog-1.jpg'
import Blog2 from './blog-2.jpg'
import Blog3 from './blog-3.jpg'


export {bgHeader, Logo, BgShap, Ab1, Ab2, SerBg1, SerBg2, SerBg3, SerBg4, MenuItem1, MenuItem2, MenuItem3, MenuItem4, MenuItem5, MenuItem6, MenuItem7, MenuItem8, MenuItem9, MenuItem10, Member1, Member2, Member3, Member4, VideoImg, Blog1, Blog2, Blog3}